name: Build Unity project and deploy to server
on: 
  push:
    branches: [ devops, develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
#     - name: Build process
#       uses: game-ci/unity-builder@v2
#       env:
#         UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#       with:
#         targetPlatform: WebGL
    - name: Checkout backend repo
      uses: actions/checkout@v2
      with:
        repository:  Group-9-Semester-4/ninja-game-backend
        path: backend
    - name: LIST FILE
      run: |
        cd $GITHUB_WORKSPACE ; ls -laf 
    - name: Check backend repo
      run: cd $GITHUB_WORKSPACE/backend ; ls -laf ; git status
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: |
        cd $GITHUB_WORKSPACE/backend
        mvn -B package -P prod --file pom.xml ; pwd ; ls -l
#     - name: Format Unity folders
#       run: |
#         mv $GITHUB_WORKSPACE/unity/build/WebGL/WebGL /github/workspace/ninja
#         rm -r /github/workspace/unity/*
#         mv /github/workspace/ninja /github/workspace/

#     - name: Push Unity build to server
#       uses: burnett01/rsync-deployments@4.1
#       with:
#         switches: -avzr --delete
#         path: build/
#         remote_path: ~/build
#         remote_host: ${{ secrets.VPS_IP }}
#         remote_port: ${{ secrets.VPS_PORT }}
#         remote_user: ${{ secrets.VPS_USER }}
#         remote_key: ${{ secrets.VPS_PRIVATE_KEY }}
