name: Build WebGL Unity project from the main branch and upload as artifact
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_WEB_HOST: ${{ secrets.UNITY_WEB_HOST }}
      UNITY_API_PORT: ${{ secrets.UNITY_API_PORT }}
      UNITY_SOCKET_PORT: ${{ secrets.UNITY_SOCKET_PORT }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Build Unity
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: WebGL
    - name: Upload WebGL Unity build as artifact    
      uses: actions/upload-artifact@v2
      with:
        name: unity_webgl_main
        path: build
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: Group-9-Semester-4/ninja-game-backend
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: build-backend-main
