name: Build WebGL Unity project from the develop branch and upload as artifact
on: 
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_WEB_HOST: ${{ secrets.UNITY_WEB_HOST }}
      UNITY_API_PORT: ${{ secrets.UNITY_API_PORT }}
      UNITY_SOCKET_PORT: ${{ secrets.UNITY_SOCKET_PORT }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Execute renaming for env doesnt work
      run: |
        cd $GITHUB_WORKSPACE/Assets/Scripts/Game/ ; 
        sed -i 's/localhost/167.71.40.34/g' StartScene.cs ;
        sed -i 's/8081/25555/g' StartScene.cs ;
        cd $GITHUB_WORKSPACE/Assets/API/ ;
        sed -i 's/localhost/167.71.40.34/g' APIClient.cs ;
    - name: Caching
      uses: actions/cache@v2
      with:
        path: $GITHUB_WORKSPACE/Library
        key: Library
    - name: Build Unity
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: WebGL
        allowDirtyBuild: true
    - name: Upload WebGL Unity build as artifact    
      uses: actions/upload-artifact@v2
      with:
        name: unity_webgl_develop
        path: build
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        repository: Group-9-Semester-4/ninja-game-backend
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: build-backend-develop
