name: Build Unity project and upload as artifact
on: 
  push:
    branches: [ devops, develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build process
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: WebGL
    - uses: actions/upload-artifact@v2
      with:
        name: unity_webgl_latest
        path: build
